### ISSUE TITLE
UI/UX: Introduce Zoomable Time series Chart in Dashboard Portfolio

### ISSUE THREAD

**Issue by NageswaraRaoSanika** [ChorusOne/anthem#108]
**Problem**

Current Portfolio widget is showing insights in particular timeframe, and if user wants to read/inspect the data for particular time range its getting hard to read/analyse the values
https://anthem.chorus.one/cosmos/total?address=cosmos15urq2dtp9qce4fyc85m6upwm9xul3049um7trd

**Proposed Solution**

Introduce Zoomable Time series chart to support Click & Drag in the chart to zoom in and inspect the data in particular time frame

Reference: https://www.highcharts.com/demo/line-time-series

**Comment by sertsedat** [comment]
simply adding `zoomType: 'x'`  to options.chart in `getHighchartsChartOptions`  function would solve this. 

https://github.com/ChorusOne/anthem/blob/342a42dab5ee91d2e230b149b333f37a55e42702/packages/client/src/tools/chart-utils.ts#L84

**Comment by FelixLutsch** [comment]
Hey @NageswaraRaoSanika and @sertsedat,

We finally got around to implementing this! You can try it out on any chart in Anthem by marking the area you'd like to zoom in on with your cursor. 

Thanks for your contribution to Anthem! I will be closing this issue now.
