### ISSUE TITLE
[Oasis: Staking] Broken hyperlinks shown in "Delegation Transaction Confirmed" window

### ISSUE THREAD

**Issue by sbellem** [ChorusOne/anthem#144]
* The link to copy the transaction hash does not work. The clip board will remain unchanged after clicking the link.
* The link to the block explorer leads to https://www.oasisscan.com/transactions/undefined, which gives a server error.

The window being referred to is:

![image](https://user-images.githubusercontent.com/125458/100677993-1bbc3f00-3364-11eb-8b56-fa851d5edc84.png)

**To Reproduce**
1. Stake ROSE tokens.
2. Click the links.
2. See errors.

**Expected behavior**
* Transaction hash should be copied to clipboard.
* Link to block explorer should go the transaction on block explorer, e.g.: https://www.oasisscan.com/transactions/c8c325a32b41981d6317543d2ad829d9c69333f885345ddb94b4ab40bb02922c

**Comment by FelixLutsch** [comment]
This has been resolved a while back, thanks for bringing this up!
